# Use root/examplerootpass as user/password credentials
services:
  spring:
    build:
      context:  ./todolist
      dockerfile: Dockerfile
    volumes:
      - ./todolist:/app
      - ./todolist/.m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005
    restart: unless-stopped
    networks:
      - default
          
networks:
  default:
    driver: bridge


  
  
