# Use root/examplerootpass as user/password credentials
services:
  spring:
    build:
      context:  ./todolist
      dockerfile: Dockerfile
    volumes:
      - ./todolist:/app
      - ./todolist/.m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005
    restart: unless-stopped
    environment:
      COGNITO_JWKS_URL: ${COGNITO_JWKS_URL}
      EXTERNAL_AUTH_TOKEN_URL: ${EXTERNAL_AUTH_TOKEN_URL}
      EXTERNAL_AUTH_CLIENT_CREDENTIALS: ${EXTERNAL_AUTH_CLIENT_CREDENTIALS}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - default
          
networks:
  default:
    driver: bridge


  
  
